# Generated by Django 2.2 on 2019-05-10 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_diario', '0002_auto_20190510_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diariocontable',
            name='banco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diarios_contables', to='contabilidad_bancos.Banco'),
        ),
        migrations.AlterField(
            model_name='diariocontable',
            name='cuenta_bancaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diarios_contables', to='contabilidad_bancos.CuentaBancariaBanco'),
        ),
    ]
