# Generated by Django 2.2 on 2019-05-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_diario', '0003_auto_20190510_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='diariocontable',
            name='tipo',
            field=models.CharField(choices=[('Venta', 'Venta'), ('Compra', 'Compra'), ('Efectivo', 'Efectivo'), ('Banco', 'Banco'), ('General', 'General')], default='General', max_length=120),
        ),
    ]
