# Generated by Django 2.2.3 on 2019-07-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_diario', '0004_diariocontable_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diariocontable',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
    ]
