# Generated by Django 2.1.5 on 2019-03-27 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('puntos_venta', '0001_initial'),
        ('terceros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArqueoCaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('dolares', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dolares_tasa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_tarjeta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nro_voucher', models.PositiveIntegerField(default=0)),
                ('punto_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bases_disponibles', to='puntos_venta.PuntoVenta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bases_disponibles_entregadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BaseDisponibleDenominacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField()),
                ('cantidad', models.PositiveIntegerField()),
                ('valor', models.DecimalField(decimal_places=0, max_digits=10)),
                ('arqueo_caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_dia_siguiente', to='cajas.ArqueoCaja')),
            ],
        ),
        migrations.CreateModel(
            name='BilleteMoneda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(0, 'BILLETES'), (1, 'MONEDAS')])),
                ('valor', models.DecimalField(decimal_places=0, max_digits=10)),
                ('activo', models.BooleanField(default=False)),
            ],
            options={
                'permissions': [['list_billetemoneda', 'Puede listar Billetes Monedas']],
            },
        ),
        migrations.CreateModel(
            name='ConceptoOperacionCaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('I', 'Ingreso'), ('E', 'Egreso')], max_length=3)),
                ('grupo', models.CharField(choices=[('A', 'Acompañantes'), ('C', 'Colaboradores'), ('P', 'Proveedores'), ('T', 'Taxis'), ('O', 'Otros')], max_length=3)),
                ('descripcion', models.CharField(max_length=300)),
            ],
            options={
                'permissions': [['list_conceptooperacioncaja', 'Puede listar Conceptos Operaciones Caja']],
            },
        ),
        migrations.CreateModel(
            name='EfectivoEntregaDenominacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField()),
                ('cantidad', models.PositiveIntegerField()),
                ('valor', models.DecimalField(decimal_places=0, max_digits=10)),
                ('arqueo_caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entrega_efectivo', to='cajas.ArqueoCaja')),
            ],
        ),
        migrations.CreateModel(
            name='OperacionCaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_operaciones', models.CharField(max_length=300)),
                ('descripcion', models.CharField(max_length=100)),
                ('observacion', models.TextField(null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('concepto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_caja', to='cajas.ConceptoOperacionCaja')),
                ('cuenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_caja', to='terceros.Cuenta')),
                ('punto_venta_turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_caja', to='puntos_venta.PuntoVentaTurno')),
                ('tercero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_caja', to='terceros.Tercero')),
            ],
            options={
                'permissions': [['list_operacioncaja', 'Puede listar Operaciones Caja']],
            },
        ),
        migrations.CreateModel(
            name='TransaccionCaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('concepto', models.TextField()),
                ('tipo', models.CharField(blank=True, choices=[('I', 'Ingreso'), ('E', 'Egreso')], max_length=3, null=True)),
                ('tipo_dos', models.CharField(blank=True, choices=[('SER_ACOM', 'Venta Servicios'), ('CAM_TIE_SER_ACOM', 'Cambio Tiempo Servicio Acompañanate'), ('CAM_HABITACION', 'Cambio de Habitacion Servicio'), ('LIQ_ACOM', 'Liquidacion Acompañante'), ('ANU_SER_ACOM', 'Anulacion Servicio Acompañante'), ('BASE_INI', 'Base Inicial'), ('OPE_CAJ_EGR', 'Operación Caja Egreso'), ('OPE_CAJ_ING', 'Operación Caja Ingreso')], max_length=30, null=True)),
                ('valor_efectivo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_tarjeta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('franquicia', models.CharField(max_length=30, null=True)),
                ('nro_autorizacion', models.CharField(max_length=30, null=True)),
                ('punto_venta_turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_caja', to='puntos_venta.PuntoVentaTurno')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='operacioncaja',
            name='transacciones_caja',
            field=models.ManyToManyField(related_name='operaciones_caja', to='cajas.TransaccionCaja'),
        ),
        migrations.AlterUniqueTogether(
            name='billetemoneda',
            unique_together={('valor', 'tipo')},
        ),
    ]
