# Generated by Django 2.2.7 on 2019-11-20 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_diario', '0001_initial'),
        ('cajas', '0002_conceptooperacioncaja_tipo_comprobante_contable_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conceptooperacioncaja',
            name='cuenta_contable_debito',
        ),
        migrations.AddField(
            model_name='conceptooperacioncaja',
            name='diario_contable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conceptos_operaciones_caja', to='contabilidad_diario.DiarioContable'),
        ),
    ]
