# Generated by Django 2.0.2 on 2018-08-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0002_auto_20180717_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientodineropdv',
            name='tipo_dos',
            field=models.CharField(blank=True, choices=[('SER_ACOM', 'Venta Servicios'), ('CAM_TIE_SER_ACOM', 'Cambio Tiempo Servicio Acompañanate'), ('CAM_HABITACION', 'Cambio de Habitacion Servicio'), ('LIQ_ACOM', 'Liquidacion Acompañante'), ('ANU_SER_ACOM', 'Anulacion Servicio Acompañante'), ('BASE_INI', 'Base Inicial')], max_length=30, null=True),
        ),
    ]
