# Generated by Django 2.0.2 on 2018-06-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0002_movimientodineroservicio_nro_autorizacio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientodineroservicio',
            name='nro_autorizacio',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
