# Generated by Django 2.1.5 on 2019-03-31 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0002_transaccioncaja_nro_vauchers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacioncaja',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
