# Generated by Django 2.2.7 on 2019-11-23 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_cuentas', '0001_initial'),
        ('cajas', '0003_auto_20191120_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conceptooperacioncaja',
            name='puntos_de_venta',
        ),
        migrations.AddField(
            model_name='conceptooperacioncaja',
            name='cuenta_contable_contrapartida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad_cuentas.CuentaContable'),
        ),
        migrations.DeleteModel(
            name='ConceptoOperacionCajaPuntoVenta',
        ),
    ]
