# Generated by Django 2.1.5 on 2019-03-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0003_auto_20190313_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccioncaja',
            name='creado_por',
        ),
    ]
