# Generated by Django 2.1.5 on 2019-04-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0004_auto_20190402_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arqueocaja',
            name='dolares',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='arqueocaja',
            name='dolares_tasa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='arqueocaja',
            name='valor_tarjeta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
