# Generated by Django 2.1.5 on 2019-03-14 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0004_remove_transaccioncaja_creado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacioncaja',
            name='movimiento_dinero',
        ),
    ]
