# Generated by Django 2.2.7 on 2019-11-23 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0001_initial'),
        ('cajas', '0004_auto_20191123_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptooperacioncaja',
            name='tercero_cuenta_contrapartida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conceptos_operaciones_caja', to='terceros.Tercero'),
        ),
    ]
