# Generated by Django 2.0.2 on 2018-08-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0004_auto_20180807_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billetemoneda',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'BILLETES'), (1, 'MONEDAS')]),
        ),
    ]
