# Generated by Django 2.0.2 on 2018-06-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0004_auto_20180624_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientodineroservicio',
            name='franquicia',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
