# Generated by Django 2.0.2 on 2018-06-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0005_auto_20180624_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientodineroservicio',
            name='concepto',
            field=models.TextField(),
        ),
    ]
