# Generated by Django 2.1.5 on 2019-04-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0005_auto_20190402_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccioncaja',
            name='tipo',
            field=models.CharField(choices=[('I', 'Ingreso'), ('E', 'Egreso')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='transaccioncaja',
            name='tipo_dos',
            field=models.CharField(choices=[('SER_ACOM', 'Venta Servicios'), ('CAM_TIE_SER_ACOM', 'Cambio Tiempo Servicio Acompañanate'), ('CAM_HABITACION', 'Cambio de Habitacion Servicio'), ('LIQ_ACOM', 'Liquidacion Acompañante'), ('ANU_SER_ACOM', 'Anulacion Servicio Acompañante'), ('BASE_INI', 'Base Inicial'), ('OPE_CAJ_EGR', 'Operación Caja Egreso'), ('OPE_CAJ_ING', 'Operación Caja Ingreso')], max_length=30, null=True),
        ),
    ]
