# Generated by Django 2.0.2 on 2018-08-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0005_auto_20180807_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoOperacionCaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
            ],
        ),
    ]
