# Generated by Django 2.1.5 on 2019-03-19 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0005_remove_operacioncaja_movimiento_dinero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientodineropdv',
            name='arqueo_caja',
        ),
        migrations.RemoveField(
            model_name='movimientodineropdv',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='movimientodineropdv',
            name='liquidacion',
        ),
        migrations.RemoveField(
            model_name='movimientodineropdv',
            name='punto_venta',
        ),
        migrations.RemoveField(
            model_name='movimientodineropdv',
            name='servicios',
        ),
        migrations.DeleteModel(
            name='MovimientoDineroPDV',
        ),
    ]
