# Generated by Django 2.2.7 on 2019-11-24 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puntos_venta', '0001_initial'),
        ('cajas', '0005_conceptooperacioncaja_tercero_cuenta_contrapartida'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoOperacionCajaPuntoVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para_cierre_caja', models.BooleanField(default=False)),
                ('concepto_operacion_caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cajas.ConceptoOperacionCaja')),
                ('punto_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='puntos_venta.PuntoVenta')),
            ],
        ),
        migrations.AddField(
            model_name='conceptooperacioncaja',
            name='puntos_de_venta',
            field=models.ManyToManyField(through='cajas.ConceptoOperacionCajaPuntoVenta', to='puntos_venta.PuntoVenta'),
        ),
    ]
