# Generated by Django 2.1.5 on 2019-03-26 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puntos_venta', '0001_initial'),
        ('cajas', '0006_auto_20190318_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operacioncaja',
            options={'permissions': [['list_operacioncaja', 'Puede listar Operaciones Caja']]},
        ),
        migrations.RemoveField(
            model_name='operacioncaja',
            name='punto_venta',
        ),
        migrations.AddField(
            model_name='operacioncaja',
            name='punto_venta_turno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_caja', to='puntos_venta.PuntoVentaTurno'),
            preserve_default=False,
        ),
    ]
