# Generated by Django 2.1.5 on 2019-04-07 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puntos_venta', '0003_puntoventaturno_turno_anterior'),
        ('cajas', '0006_auto_20190402_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arqueocaja',
            old_name='nro_voucher',
            new_name='nro_voucher_entregados',
        ),
        migrations.RenameField(
            model_name='arqueocaja',
            old_name='dolares',
            new_name='saldo',
        ),
        migrations.RenameField(
            model_name='arqueocaja',
            old_name='valor_tarjeta',
            new_name='valor_dolares_entregados',
        ),
        migrations.RemoveField(
            model_name='arqueocaja',
            name='punto_venta',
        ),
        migrations.RemoveField(
            model_name='arqueocaja',
            name='usuario',
        ),
        migrations.AddField(
            model_name='arqueocaja',
            name='observacion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='arqueocaja',
            name='punto_venta_turno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='arqueos_caja', to='puntos_venta.PuntoVentaTurno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arqueocaja',
            name='valor_pago_efectivo_a_entregar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='arqueocaja',
            name='valor_pago_tarjeta_a_entregar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='arqueocaja',
            name='valor_tarjeta_entregados',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='basedisponibledenominacion',
            name='cantidad_recibida',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basedisponibledenominacion',
            name='valor_total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='efectivoentregadenominacion',
            name='valor_total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='basedisponibledenominacion',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='basedisponibledenominacion',
            name='valor',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billetemoneda',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'BILLETES'), (2, 'MONEDAS')]),
        ),
        migrations.AlterField(
            model_name='efectivoentregadenominacion',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='efectivoentregadenominacion',
            name='valor',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
