# Generated by Django 2.0.2 on 2018-08-08 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0006_conceptooperacioncaja'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conceptooperacioncaja',
            options={'permissions': [['list_conceptooperacioncaja', 'Puede listar Conceptos Operaciones Caja']]},
        ),
    ]
