# Generated by Django 2.1.5 on 2019-03-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0007_auto_20190326_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacioncaja',
            name='transacciones_caja',
            field=models.ManyToManyField(related_name='operaciones_caja', to='cajas.TransaccionCaja'),
        ),
    ]
