# Generated by Django 2.0.2 on 2018-08-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0007_auto_20180808_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptooperacioncaja',
            name='tipo',
            field=models.CharField(choices=[('I', 'Ingreso'), ('E', 'Egreso')], default='E', max_length=3),
            preserve_default=False,
        ),
    ]
