# Generated by Django 2.1.5 on 2019-04-20 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0008_arqueocaja_nro_voucher_a_entregar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arqueocaja',
            name='saldo',
        ),
    ]
