# Generated by Django 2.0.2 on 2018-08-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0008_conceptooperacioncaja_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptooperacioncaja',
            name='grupo',
            field=models.CharField(choices=[('A', 'Acompañantes'), ('C', 'Colaboradores'), ('P', 'Proveedores'), ('O', 'Otros')], default='A', max_length=3),
            preserve_default=False,
        ),
    ]
