# Generated by Django 2.0.2 on 2018-08-09 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0001_initial'),
        ('cajas', '0009_conceptooperacioncaja_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionCaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('observacion', models.TextField()),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_caja', to='terceros.Cuenta')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_caja', to='terceros.Tercero')),
            ],
        ),
        migrations.AlterField(
            model_name='conceptooperacioncaja',
            name='grupo',
            field=models.CharField(choices=[('A', 'Acompañantes'), ('C', 'Colaboradores'), ('P', 'Proveedores'), ('T', 'Taxis'), ('O', 'Otros')], max_length=3),
        ),
    ]
