# Generated by Django 2.1.5 on 2019-04-22 00:18

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0009_remove_arqueocaja_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacioncaja',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='operacioncaja',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
