# Generated by Django 2.1.5 on 2019-04-24 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0010_auto_20190421_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arqueocaja',
            name='punto_venta_turno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='arqueo_caja', to='puntos_venta.PuntoVentaTurno'),
        ),
    ]
