# Generated by Django 2.0.2 on 2018-08-09 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0010_auto_20180808_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacioncaja',
            name='grupo_operaciones',
            field=models.CharField(default='temporal', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operacioncaja',
            name='cuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_caja', to='terceros.Cuenta'),
        ),
        migrations.AlterField(
            model_name='operacioncaja',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='operacioncaja',
            name='tercero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_caja', to='terceros.Tercero'),
        ),
    ]
