# Generated by Django 2.0.2 on 2018-08-09 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0011_auto_20180808_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacioncaja',
            name='concepto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_caja', to='cajas.ConceptoOperacionCaja'),
        ),
    ]
