# Generated by Django 2.0.2 on 2018-08-09 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puntos_venta', '0003_puntoventa_usuario_actual'),
        ('cajas', '0012_operacioncaja_concepto'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacioncaja',
            name='punto_venta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_caja', to='puntos_venta.PuntoVenta'),
        ),
    ]
