# Generated by Django 2.1.5 on 2019-04-27 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0012_conceptooperacioncaja_en_cierre_de_caja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conceptooperacioncaja',
            name='en_cierre_de_caja',
        ),
    ]
