# Generated by Django 2.0.2 on 2018-08-09 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0013_operacioncaja_punto_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacioncaja',
            name='movimiento_dinero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_caja', to='cajas.MovimientoDineroPDV'),
        ),
    ]
