# Generated by Django 2.1.5 on 2019-04-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntos_venta', '0006_puntoventaturno_base_inicial_efectivo'),
        ('cajas', '0013_remove_conceptooperacioncaja_en_cierre_de_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptooperacioncaja',
            name='puntos_de_venta',
            field=models.ManyToManyField(related_name='conceptos_operaciones_caja_cierre', to='puntos_venta.PuntoVenta'),
        ),
    ]
