# Generated by Django 2.0.2 on 2018-08-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0014_operacioncaja_movimiento_dinero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacioncaja',
            name='observacion',
            field=models.TextField(null=True),
        ),
    ]
