# Generated by Django 2.2 on 2019-04-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0015_operacioncaja_reporte_independiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptooperacioncaja',
            name='reporte_independiente',
            field=models.BooleanField(default=False),
        ),
    ]
