# Generated by Django 2.0.2 on 2018-10-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0015_auto_20180809_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientodineropdv',
            name='tipo_dos',
            field=models.CharField(blank=True, choices=[('SER_ACOM', 'Venta Servicios'), ('CAM_TIE_SER_ACOM', 'Cambio Tiempo Servicio Acompañanate'), ('CAM_HABITACION', 'Cambio de Habitacion Servicio'), ('LIQ_ACOM', 'Liquidacion Acompañante'), ('ANU_SER_ACOM', 'Anulacion Servicio Acompañante'), ('BASE_INI', 'Base Inicial'), ('OPE_CAJ_EGR', 'Operación Caja Egreso'), ('OPE_CAJ_ING', 'Operación Caja Ingreso')], max_length=30, null=True),
        ),
    ]
