# Generated by Django 2.2 on 2019-04-29 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0016_conceptooperacioncaja_reporte_independiente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacioncaja',
            name='reporte_independiente',
        ),
    ]
