# Generated by Django 2.2 on 2019-04-30 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0017_remove_operacioncaja_reporte_independiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptooperacioncaja',
            name='tipo_cuenta',
            field=models.CharField(choices=[('CXC', 'Cuenta x Cobrar'), ('CXP', 'Cuenta x Pagar')], max_length=3, null=True),
        ),
    ]
