# Generated by Django 2.2 on 2019-04-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0019_auto_20190429_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacioncaja',
            name='tipo_cuenta',
            field=models.CharField(default='NA', max_length=3),
        ),
        migrations.AlterField(
            model_name='conceptooperacioncaja',
            name='tipo_cuenta',
            field=models.CharField(choices=[('CXC', 'Cuenta x Cobrar'), ('CXP', 'Cuenta x Pagar'), ('NA', 'No Aplica')], default='NA', max_length=3),
        ),
    ]
