# Generated by Django 2.1.5 on 2019-03-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipovehiculo',
            old_name='porcentaje_impuesto',
            new_name='porcentaje_iva',
        ),
        migrations.AddField(
            model_name='tipovehiculo',
            name='valor_impuesto_unico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
