# Generated by Django 2.1.5 on 2019-03-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroentradaparqueo',
            name='detalle',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
