# Generated by Django 2.2.7 on 2019-12-13 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0002_modalidadfracciontiempo_tipo_comprobante_contable_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipovehiculo',
            name='empresa',
        ),
    ]
