# Generated by Django 2.1.5 on 2019-03-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0002_auto_20190328_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipovehiculo',
            name='nombre',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='modalidadfracciontiempodetalle',
            unique_together={('modalidad_fraccion_tiempo', 'minutos')},
        ),
    ]
