# Generated by Django 2.1.5 on 2019-04-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0002_auto_20190329_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroentradaparqueo',
            name='valor_impuesto_unico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='registroentradaparqueo',
            name='valor_iva_parqueadero',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='registroentradaparqueo',
            name='valor_parqueadero',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
