# Generated by Django 2.1.5 on 2019-03-29 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0003_auto_20190328_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalidadfracciontiempodetalle',
            name='modalidad_fraccion_tiempo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fracciones', to='parqueadero.ModalidadFraccionTiempo'),
        ),
    ]
