# Generated by Django 2.2.7 on 2019-12-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_impuestos', '0001_initial'),
        ('parqueadero', '0003_remove_tipovehiculo_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalidadfracciontiempo',
            name='impuestos',
            field=models.ManyToManyField(related_name='modalidades_fracciones_tiempo', to='contabilidad_impuestos.Impuesto'),
        ),
    ]
