# Generated by Django 2.1.5 on 2019-04-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0003_auto_20190402_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroentradaparqueo',
            name='hora_pago',
            field=models.DateTimeField(null=True),
        ),
    ]
