# Generated by Django 2.2.7 on 2019-12-14 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0004_modalidadfracciontiempo_impuestos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipovehiculo',
            name='porcentaje_iva',
        ),
        migrations.RemoveField(
            model_name='tipovehiculo',
            name='valor_impuesto_unico',
        ),
    ]
