# Generated by Django 2.1.5 on 2019-03-29 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0004_auto_20190328_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipovehiculo',
            options={'permissions': [['list_tipovehiculo', 'Puede listar tipos vehiculos']]},
        ),
    ]
