# Generated by Django 2.2 on 2019-05-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0004_registroentradaparqueo_hora_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalidadfracciontiempo',
            name='domingo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modalidadfracciontiempo',
            name='jueves',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modalidadfracciontiempo',
            name='lunes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modalidadfracciontiempo',
            name='martes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modalidadfracciontiempo',
            name='miercoles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modalidadfracciontiempo',
            name='sabado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modalidadfracciontiempo',
            name='todo_el_dia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modalidadfracciontiempo',
            name='viernes',
            field=models.BooleanField(default=False),
        ),
    ]
