# Generated by Django 2.1.5 on 2019-03-29 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0005_auto_20190328_2333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modalidadfracciontiempo',
            options={'permissions': [['list_modalidadfracciontiempo', 'Puede listar modalidades fracciones tiempos']]},
        ),
        migrations.AlterModelOptions(
            name='modalidadfracciontiempodetalle',
            options={'permissions': [['list_modalidadfracciontiempodetalle', 'Puede listar modalidades fracciones tiempos detalles']]},
        ),
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': [['list_vehiculo', 'Puede listar vehiculos']]},
        ),
    ]
