# Generated by Django 2.2 on 2019-05-07 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0005_auto_20190506_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalidadfracciontiempo',
            name='hora_final',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='modalidadfracciontiempo',
            name='hora_inicio',
            field=models.TimeField(null=True),
        ),
    ]
