# Generated by Django 2.2 on 2019-05-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0006_auto_20190506_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modalidadfracciontiempo',
            name='hora_final',
        ),
        migrations.RemoveField(
            model_name='modalidadfracciontiempo',
            name='todo_el_dia',
        ),
        migrations.AddField(
            model_name='modalidadfracciontiempo',
            name='numero_horas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='modalidadfracciontiempo',
            name='domingo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='modalidadfracciontiempo',
            name='jueves',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='modalidadfracciontiempo',
            name='lunes',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='modalidadfracciontiempo',
            name='martes',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='modalidadfracciontiempo',
            name='miercoles',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='modalidadfracciontiempo',
            name='sabado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='modalidadfracciontiempo',
            name='viernes',
            field=models.BooleanField(default=True),
        ),
    ]
