# Generated by Django 2.0.2 on 2018-07-17 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('puntos_venta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cajero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mis_ventas_cajero', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mis_compras', to=settings.AUTH_USER_MODEL)),
                ('mesero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mis_ventas', to=settings.AUTH_USER_MODEL)),
                ('punto_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_ventas', to='puntos_venta.PuntoVenta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('precio_venta_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_ventas', to='productos.Producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_produtos', to='ventas.Venta')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
