# Generated by Django 2.2.7 on 2019-11-19 02:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('cajas', '0001_initial'),
        ('terceros', '0001_initial'),
        ('productos', '0001_initial'),
        ('inventarios', '0001_initial'),
        ('puntos_venta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cuenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras_productos', to='terceros.Cuenta')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_productos', to='empresas.Empresa')),
                ('movimientos', models.ManyToManyField(related_name='ventas_productos', to='inventarios.MovimientoInventario')),
                ('punto_venta_turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_productos', to='puntos_venta.PuntoVentaTurno')),
                ('transacciones_caja', models.ManyToManyField(related_name='ventas_productos', to='cajas.TransaccionCaja')),
            ],
            options={
                'permissions': [['list_ventaproducto', 'Puede listar ventas productos']],
            },
        ),
        migrations.CreateModel(
            name='VentaProductoDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comision', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cuenta_comision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comisiones_x_productos', to='terceros.Cuenta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='productos.Producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='ventas.VentaProducto')),
            ],
            options={
                'permissions': [['list_ventaproductodetalle', 'Puede listar ventas productos detalles']],
            },
        ),
    ]
