# Generated by Django 2.1.5 on 2019-03-19 03:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('puntos_venta', '0001_initial'),
        ('terceros', '0003_auto_20190313_1033'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaProductoDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cajero',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='mesero',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='punto_venta',
        ),
        migrations.RemoveField(
            model_name='ventaproducto',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='ventaproducto',
            name='costo_total',
        ),
        migrations.RemoveField(
            model_name='ventaproducto',
            name='costo_unitario',
        ),
        migrations.RemoveField(
            model_name='ventaproducto',
            name='precio_venta_total',
        ),
        migrations.RemoveField(
            model_name='ventaproducto',
            name='precio_venta_unitario',
        ),
        migrations.RemoveField(
            model_name='ventaproducto',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='ventaproducto',
            name='venta',
        ),
        migrations.AddField(
            model_name='ventaproducto',
            name='cuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras_productos', to='terceros.Cuenta'),
        ),
        migrations.AddField(
            model_name='ventaproducto',
            name='punto_venta_turno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_productos', to='puntos_venta.PuntoVentaTurno'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
        migrations.AddField(
            model_name='ventaproductodetalle',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='ventas.VentaProducto'),
        ),
    ]
