# Generated by Django 2.1.5 on 2019-03-29 02:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaParqueadero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('valor_parqueadero', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('valor_iva_parqueadero', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('detalle', models.CharField(max_length=500)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parqueadero.Vehiculo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
