# Generated by Django 2.1.5 on 2019-03-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20190318_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaproductodetalle',
            name='estado',
            field=models.PositiveIntegerField(choices=[(1, 'Vendido'), (2, 'Devolución'), (3, 'Anulado')], default=0),
        ),
    ]
