# Generated by Django 2.1.5 on 2019-03-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_ventaparqueadero'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaparqueadero',
            name='valor_impuesto_unico',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
