# Generated by Django 2.1.5 on 2019-04-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0003_auto_20190331_1612'),
        ('ventas', '0003_auto_20190330_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaproducto',
            name='transacciones_caja',
            field=models.ManyToManyField(related_name='ventas_productos', to='cajas.TransaccionCaja'),
        ),
    ]
