# Generated by Django 2.1.5 on 2019-03-24 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20190323_0018'),
        ('ventas', '0003_ventaproductodetalle_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaproductodetalle',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='productos.Producto'),
            preserve_default=False,
        ),
    ]
