# Generated by Django 2.1.5 on 2019-03-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0006_auto_20190323_1412'),
        ('ventas', '0004_ventaproductodetalle_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventaproductodetalle',
            name='estado',
        ),
        migrations.AddField(
            model_name='ventaproducto',
            name='movimientos',
            field=models.ManyToManyField(related_name='ventas_productos', to='inventarios.MovimientoInventario'),
        ),
    ]
