# Generated by Django 2.2 on 2019-05-02 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('ventas', '0004_ventaproducto_transacciones_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaproducto',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_productos', to='empresas.Empresa'),
        ),
    ]
