# Generated by Django 2.1.5 on 2019-03-25 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_auto_20190324_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ventaproducto',
            options={'permissions': [['list_ventaproducto', 'Puede listar ventas productos']]},
        ),
        migrations.AlterModelOptions(
            name='ventaproductodetalle',
            options={'permissions': [['list_ventaproductodetalle', 'Puede listar ventas productos detalles']]},
        ),
    ]
