# Generated by Django 2.2.7 on 2019-11-19 02:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cajas', '0001_initial'),
        ('habitaciones', '0001_initial'),
        ('terceros', '0001_initial'),
        ('empresas', '0001_initial'),
        ('puntos_venta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('estado', models.IntegerField(choices=[(1, 'En Servicio'), (2, 'Terminado'), (3, 'Anulado'), (4, 'Solicitud Anulación')], default=0)),
                ('hora_inicio', models.DateTimeField(null=True)),
                ('hora_final', models.DateTimeField(null=True)),
                ('hora_final_real', models.DateTimeField(null=True)),
                ('hora_anulacion', models.DateTimeField(null=True)),
                ('tiempo_minutos', models.PositiveIntegerField(default=0)),
                ('categoria', models.CharField(max_length=120, null=True)),
                ('valor_servicio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_servicio_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_habitacion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacion_anulacion', models.TextField(null=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='terceros.Cuenta')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='empresas.Empresa')),
                ('habitacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='habitaciones.Habitacion')),
                ('punto_venta_turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_servicios', to='puntos_venta.PuntoVentaTurno')),
                ('servicio_anterior', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicio_siguiente', to='servicios.Servicio')),
                ('transacciones_caja', models.ManyToManyField(related_name='servicios', to='cajas.TransaccionCaja')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BitacoraServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('habitacion_nombre', models.CharField(blank=True, max_length=300, null=True)),
                ('habitacion_anterior_nombre', models.CharField(blank=True, max_length=300, null=True)),
                ('habitacion_nueva_nombre', models.CharField(blank=True, max_length=300, null=True)),
                ('tiempo_contratado_anterior', models.PositiveIntegerField(blank=True, null=True)),
                ('tiempo_contratado_nuevo', models.PositiveIntegerField(blank=True, null=True)),
                ('tiempo_contratado', models.PositiveIntegerField(blank=True, null=True)),
                ('hora_evento', models.DateTimeField(blank=True, null=True)),
                ('tiempo_minutos_recorridos', models.PositiveIntegerField(blank=True, null=True)),
                ('concepto', models.CharField(max_length=200)),
                ('observacion', models.TextField(null=True)),
                ('punto_venta_turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bitacoras_servicios', to='puntos_venta.PuntoVentaTurno')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras_servicio', to='servicios.Servicio')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
