# Generated by Django 2.1.5 on 2019-03-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='transacciones_caja',
            field=models.ManyToManyField(related_name='servicios', to='cajas.TransaccionCaja'),
        ),
    ]
