# Generated by Django 2.0.2 on 2018-06-10 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0002_auto_20180319_0224'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='habitacion',
        ),
        migrations.AddField(
            model_name='ventaservicio',
            name='habitacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='habitaciones.Habitacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventaservicio',
            name='venta_servicio_inicial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cambios_venta_servicio', to='servicios.VentaServicio'),
        ),
    ]
