# Generated by Django 2.1.5 on 2019-03-13 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puntos_venta', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='empresa',
        ),
        migrations.AddField(
            model_name='servicio',
            name='punto_venta_turno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='venta_servicios', to='puntos_venta.PuntoVentaTurno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='habitacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='habitaciones.Habitacion'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='hora_anulacion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='hora_final',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='hora_final_real',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='hora_inicio',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='observacion_anulacion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='servicio_anterior',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicio_siguiente', to='servicios.Servicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='valor_habitacion',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='valor_iva_habitacion',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='valor_servicio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
