# Generated by Django 2.0.2 on 2018-06-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20180610_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaservicio',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Inicio'), (1, 'En Servicio'), (2, 'Terminado'), (3, 'Anulado')], default=0),
        ),
    ]
