# Generated by Django 2.1.5 on 2019-03-29 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puntos_venta', '0001_initial'),
        ('servicios', '0002_auto_20190327_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitacoraservicio',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bitacoraservicio',
            name='punto_venta',
        ),
        migrations.AddField(
            model_name='bitacoraservicio',
            name='punto_venta_turno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bitacoras_servicios', to='puntos_venta.PuntoVentaTurno'),
            preserve_default=False,
        ),
    ]
