# Generated by Django 2.1.5 on 2019-03-19 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20190313_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='punto_venta_turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_servicios', to='puntos_venta.PuntoVentaTurno'),
        ),
    ]
