# Generated by Django 2.1.5 on 2019-03-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_auto_20190328_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='comision',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
