# Generated by Django 2.1.5 on 2019-03-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0009_remove_transaccioncaja_servicios'),
        ('servicios', '0003_auto_20190318_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='transacciones_caja',
            field=models.ManyToManyField(related_name='transacciones_caja', to='cajas.TransaccionCaja'),
        ),
    ]
