# Generated by Django 2.0.2 on 2018-06-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_ventaservicio_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaservicio',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Activo'), (1, 'Terminado')], default=0),
        ),
    ]
