# Generated by Django 2.1.5 on 2019-04-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_servicio_comision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='valor_habitacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='valor_iva_habitacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='valor_servicio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
