# Generated by Django 2.0.2 on 2018-06-11 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_auto_20180611_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='terceros.Cuenta'),
        ),
    ]
