# Generated by Django 2.0.2 on 2018-06-11 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_auto_20180611_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='venta_servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='servicios.VentaServicio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicio',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='terceros.Cuenta'),
        ),
    ]
