# Generated by Django 2.2 on 2019-05-02 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('servicios', '0005_auto_20190402_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='empresas.Empresa'),
        ),
    ]
