# Generated by Django 2.0.2 on 2018-06-11 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_auto_20180611_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaservicio',
            name='habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_servicios', to='habitaciones.Habitacion'),
        ),
    ]
