# Generated by Django 2.0.2 on 2018-06-12 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_auto_20180611_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='venta_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='servicios.VentaServicio'),
        ),
    ]
