# Generated by Django 2.0.2 on 2018-06-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0008_auto_20180612_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaservicio',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Activo'), (2, 'Iniciado'), (3, 'Terminado')], default=0),
        ),
    ]
