# Generated by Django 2.0.2 on 2018-06-26 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0009_auto_20180617_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='servicio_anterior',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicio_siguiente', to='servicios.Servicio'),
        ),
    ]
