# Generated by Django 2.0.2 on 2018-06-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0010_servicio_servicio_anterior'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
