# Generated by Django 2.0.2 on 2018-06-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0011_servicio_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Inicio'), (1, 'En Servicio'), (2, 'Terminado'), (3, 'Anulado'), (4, 'Solicitud Anulación')], default=0),
        ),
    ]
