# Generated by Django 2.0.2 on 2018-06-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0012_auto_20180627_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='hora_anulacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='hora_final_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
