# Generated by Django 2.0.2 on 2018-07-05 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0014_auto_20180627_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventaservicio',
            name='valor_total',
        ),
    ]
