# Generated by Django 2.0.2 on 2018-07-05 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0015_remove_ventaservicio_valor_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventaservicio',
            name='valor_habitaciones',
        ),
        migrations.RemoveField(
            model_name='ventaservicio',
            name='valor_iva_habitaciones',
        ),
        migrations.RemoveField(
            model_name='ventaservicio',
            name='valor_servicios',
        ),
    ]
