# Generated by Django 2.0.2 on 2018-07-06 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0017_remove_servicio_valor_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventaservicio',
            name='venta_servicio_inicial',
        ),
    ]
