# Generated by Django 2.0.2 on 2018-07-06 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0019_bitacoraservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoraservicio',
            name='tiempo_minutos_recorridos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
