# Generated by Django 2.0.2 on 2018-03-19 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_auto_20180319_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('estado', models.PositiveIntegerField(choices=[(0, 'Disponible'), (1, 'Ocupada'), (2, 'Sucia'), (3, 'En Mantenimiento')], default=0)),
                ('activa', models.BooleanField(default=1)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_habitaciones', to='empresas.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('valor', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Valor con Iva')),
            ],
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_habitaciones', to='habitaciones.TipoHabitacion', verbose_name='Tipo de Habitación'),
        ),
    ]
