# Generated by Django 2.1.5 on 2019-03-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipohabitacion',
            name='comision',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
