# Generated by Django 2.0.2 on 2018-03-19 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitacion',
            options={'permissions': [['list_habitacion', 'Puede listar habitaciones']]},
        ),
        migrations.AlterModelOptions(
            name='tipohabitacion',
            options={'permissions': [['list_tipohabitacion', 'Puede listar tipos habitaciones']]},
        ),
    ]
