# Generated by Django 2.1.5 on 2019-02-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0002_auto_20180801_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
