# Generated by Django 2.2 on 2019-05-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_impuestos', '0002_auto_20190510_1212'),
        ('habitaciones', '0002_tipohabitacion_comision'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipohabitacion',
            name='impuestos',
            field=models.ManyToManyField(related_name='tipos_habitaciones', to='contabilidad_impuestos.Impuesto'),
        ),
    ]
