# Generated by Django 2.0.2 on 2018-06-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0002_auto_20180319_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='estado',
            field=models.PositiveIntegerField(choices=[(0, 'Disponible'), (1, 'Ocupada'), (2, 'Sucia'), (3, 'En Mantenimiento'), (4, 'Bloqueada')], default=0),
        ),
    ]
