# Generated by Django 2.0.2 on 2018-06-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0003_auto_20180610_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='fecha_ultimo_estado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tiempo_final_servicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
