# Generated by Django 2.1.5 on 2019-02-04 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0003_habitacion_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='activo',
        ),
    ]
