# Generated by Django 2.2 on 2019-05-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0003_tipohabitacion_impuestos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipohabitacion',
            name='valor_adicional_servicio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tipohabitacion',
            name='valor',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
