# Generated by Django 2.1.5 on 2019-02-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0004_remove_habitacion_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='activa',
            field=models.BooleanField(default=False),
        ),
    ]
