# Generated by Django 2.0.2 on 2018-06-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0004_auto_20180610_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipohabitacion',
            name='porcentaje_impuesto',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Valor con Iva'),
        ),
    ]
