# Generated by Django 2.2 on 2019-05-14 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0004_auto_20190513_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipohabitacion',
            name='comision',
        ),
        migrations.RemoveField(
            model_name='tipohabitacion',
            name='porcentaje_impuesto',
        ),
    ]
