# Generated by Django 2.0.2 on 2018-06-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0005_tipohabitacion_porcentaje_impuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipohabitacion',
            name='porcentaje_impuesto',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
