# Generated by Django 2.2.3 on 2019-07-07 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0005_auto_20190514_0034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitacion',
            options={'permissions': [['list_habitacion', 'Puede listar habitaciones']], 'verbose_name_plural': 'Habitaciones'},
        ),
    ]
