# Generated by Django 2.0.2 on 2018-06-28 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0006_auto_20180612_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='tiempo_final_servicio',
        ),
    ]
