# Generated by Django 2.2.7 on 2019-11-19 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=14, unique=True)),
                ('cuenta_nivel_1', models.CharField(max_length=14)),
                ('cuenta_nivel_2', models.CharField(max_length=14)),
                ('cuenta_nivel_3', models.CharField(max_length=14)),
                ('cuenta_nivel_4', models.CharField(max_length=14)),
                ('cuenta_nivel_5', models.CharField(max_length=14)),
                ('cuenta_nivel_6', models.CharField(max_length=14)),
                ('cuenta_nivel_7', models.CharField(max_length=14)),
                ('cuenta_nivel_8', models.CharField(max_length=14)),
                ('cuenta_nivel', models.IntegerField()),
                ('descripcion', models.CharField(max_length=300)),
                ('naturaleza', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], max_length=1)),
                ('tipo', models.CharField(choices=[('T', 'Título'), ('D', 'Detalle')], max_length=1)),
                ('cuenta_padre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_hijas', to='contabilidad_cuentas.CuentaContable')),
            ],
            options={
                'permissions': [['list_cuentacontable', 'Puede listar Cuentas Contables']],
            },
        ),
    ]
