# Generated by Django 2.2 on 2019-05-08 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacontable',
            name='cuenta_padre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_hijas', to='contabilidad_cuentas.CuentaContable'),
        ),
    ]
