# Generated by Django 2.2 on 2019-05-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_cuentas', '0002_auto_20190508_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacontable',
            name='codigo',
            field=models.CharField(db_index=True, max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='cuentacontable',
            name='cuenta_nivel_1',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='cuentacontable',
            name='cuenta_nivel_2',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='cuentacontable',
            name='cuenta_nivel_3',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='cuentacontable',
            name='cuenta_nivel_4',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='cuentacontable',
            name='cuenta_nivel_5',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='cuentacontable',
            name='cuenta_nivel_6',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='cuentacontable',
            name='cuenta_nivel_7',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='cuentacontable',
            name='cuenta_nivel_8',
            field=models.CharField(max_length=14),
        ),
    ]
