# Generated by Django 2.2.7 on 2019-12-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datogeneral',
            name='nombre_aplicacion',
            field=models.CharField(default='Nombre App.', max_length=50),
        ),
    ]
