# Generated by Django 2.0.2 on 2018-07-17 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.PositiveIntegerField(choices=[(0, 'Servicios'), (1, 'Tienda')])),
                ('abierto', models.BooleanField(default=0)),
                ('bodega', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='punto_venta', to='inventarios.Bodega')),
                ('usuarios', models.ManyToManyField(related_name='mis_puntos_venta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [['list_puntoventa', 'Puede listar puntos ventas'], ['detail_puntoventa', 'Puede ver detalle punto venta']],
            },
        ),
    ]
