# Generated by Django 2.1.5 on 2019-03-09 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.PositiveIntegerField(choices=[(1, 'Servicios'), (2, 'Tienda')])),
                ('abierto', models.BooleanField(default=0)),
                ('bodega', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='punto_venta', to='inventarios.Bodega')),
                ('usuario_actual', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='punto_venta_actual', to=settings.AUTH_USER_MODEL)),
                ('usuarios', models.ManyToManyField(related_name='mis_puntos_venta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [['list_puntoventa', 'Puede listar puntos ventas']],
            },
        ),
        migrations.CreateModel(
            name='PuntoVentaTurno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('finish', models.DateTimeField(null=True)),
                ('punto_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='puntos_venta.PuntoVenta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos_punto_venta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
