# Generated by Django 2.1.5 on 2019-04-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntos_venta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoventaturno',
            name='base_inicial_efectivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='puntoventaturno',
            name='saldo_cierre_caja',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='puntoventaturno',
            name='saldo_cierre_caja_anterior',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
