# Generated by Django 2.0.2 on 2018-04-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntos_venta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntoventa',
            name='es_servicios',
        ),
        migrations.RemoveField(
            model_name='puntoventa',
            name='es_tienda',
        ),
        migrations.AddField(
            model_name='puntoventa',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(0, 'Servicios'), (1, 'Tienda')], default=0),
            preserve_default=False,
        ),
    ]
