# Generated by Django 2.0.2 on 2018-07-18 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('puntos_venta', '0002_auto_20180717_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoventa',
            name='usuario_actual',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='punto_venta_actual', to=settings.AUTH_USER_MODEL),
        ),
    ]
