# Generated by Django 2.0.2 on 2018-04-03 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puntos_venta', '0002_auto_20180403_0315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puntoventa',
            options={'permissions': [['list_puntoventa', 'Puede listar puntos ventas'], ['detail_puntoventa', 'Puede ver detalle punto venta']]},
        ),
    ]
