# Generated by Django 2.1.5 on 2019-04-03 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puntos_venta', '0002_auto_20190402_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoventaturno',
            name='turno_anterior',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='siguiente_turno', to='puntos_venta.PuntoVentaTurno'),
        ),
    ]
