# Generated by Django 2.1.5 on 2019-02-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntos_venta', '0003_puntoventa_usuario_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntoventa',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Servicios'), (2, 'Tienda')]),
        ),
    ]
