# Generated by Django 2.1.5 on 2019-04-24 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puntos_venta', '0003_puntoventaturno_turno_anterior'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puntoventaturno',
            old_name='saldo_cierre_caja',
            new_name='diferencia_cierre_caja',
        ),
        migrations.RenameField(
            model_name='puntoventaturno',
            old_name='saldo_cierre_caja_anterior',
            new_name='diferencia_cierre_caja_anterior',
        ),
    ]
