# Generated by Django 2.1.5 on 2019-04-24 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puntos_venta', '0004_auto_20190424_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntoventaturno',
            name='base_inicial_efectivo',
        ),
    ]
