# Generated by Django 2.1.5 on 2019-04-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntos_venta', '0005_remove_puntoventaturno_base_inicial_efectivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoventaturno',
            name='base_inicial_efectivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
