# Generated by Django 2.2 on 2019-05-06 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puntos_venta', '0006_puntoventaturno_base_inicial_efectivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntoventa',
            name='bodega',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='punto_venta', to='inventarios.Bodega'),
        ),
        migrations.AlterField(
            model_name='puntoventa',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Servicios'), (2, 'Tienda'), (3, 'Parqueadero')]),
        ),
    ]
