# Generated by Django 2.0.2 on 2018-06-10 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroingreso',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regitros_ingresos', to=settings.AUTH_USER_MODEL),
        ),
    ]
