# Generated by Django 2.2.7 on 2019-11-20 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad_cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('tipo_calculo_impuesto', models.IntegerField(choices=[(1, 'Porcentaje sobre el precio con impuestos incluidos'), (2, 'Porcentaje sobre el precio'), (3, 'Fijo')])),
                ('tasa_importe_venta', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('tasa_importe_compra', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('cuenta_impuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impuestos', to='contabilidad_cuentas.CuentaContable')),
                ('cuenta_impuesto_notas_credito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impuestos_notas_credito', to='contabilidad_cuentas.CuentaContable')),
            ],
            options={
                'permissions': [['list_impuesto', 'Puede listar Impuestos']],
            },
        ),
    ]
