# Generated by Django 2.2 on 2019-05-10 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_impuestos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impuesto',
            options={'permissions': [['list_impuesto', 'Puede listar Impuestos']]},
        ),
        migrations.AlterModelOptions(
            name='impuestogrupo',
            options={'permissions': [['list_impuestogrupo', 'Puede listar Grupos de Impuestos']]},
        ),
    ]
