# Generated by Django 2.2 on 2019-05-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_impuestos', '0002_auto_20190510_1212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImpuestoGrupo',
        ),
        migrations.RenameField(
            model_name='impuesto',
            old_name='importe',
            new_name='tasa_importe_compra',
        ),
        migrations.RemoveField(
            model_name='impuesto',
            name='ambito',
        ),
        migrations.AddField(
            model_name='impuesto',
            name='tasa_importe_venta',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='tipo_calculo_impuesto',
            field=models.IntegerField(choices=[(1, 'Porcentaje sobre el precio con impuestos incluidos'), (2, 'Porcentaje sobre el precio'), (3, 'Fijo')]),
        ),
    ]
