# Generated by Django 2.1.5 on 2019-03-27 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields
import inventarios.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terceros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('es_principal', models.BooleanField(default=False)),
            ],
            options={
                'permissions': [['list_bodega', 'Puede listar bodegas']],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fecha', models.DateField()),
                ('motivo', models.TextField(null=True)),
                ('detalle', models.TextField(null=True)),
                ('tipo', models.CharField(max_length=2, null=True)),
                ('cargado', models.BooleanField(default=False)),
                ('observacion', models.TextField(null=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventarios.Bodega')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventarios', to='terceros.Tercero')),
            ],
            options={
                'permissions': [['list_movimientoinventario', 'Puede listar movimientos inventario']],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventarioDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('entra_cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('entra_costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sale_cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sale_costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_unitario_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('es_ultimo_saldo', models.BooleanField(default=False)),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='inventarios.MovimientoInventario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventarios', to='productos.Producto')),
            ],
            options={
                'permissions': [['list_movimientoinventariodetalle', 'Puede listar movimiento inventario detalle']],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventarioDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('imagen_documento', imagekit.models.fields.ProcessedImageField(upload_to=inventarios.models.MovimientoInventarioDocumento.imagen_documento_upload_to)),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='inventarios.MovimientoInventario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrasladoInventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('trasladado', models.BooleanField(default=False)),
                ('estado', models.PositiveIntegerField(choices=[(1, 'Iniciado'), (2, 'Esperando Traslado'), (3, 'Verificado')], default=1)),
                ('bodega_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_mercancia_traslado', to='inventarios.Bodega')),
                ('bodega_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas_mercancia_traslado', to='inventarios.Bodega')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslado_inventario_creado', to=settings.AUTH_USER_MODEL)),
                ('movimiento_destino', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslado_recibe', to='inventarios.MovimientoInventario')),
                ('movimiento_origen', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslado_entrega', to='inventarios.MovimientoInventario')),
                ('recibido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslado_inventario_recibido', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [['list_trasladoinventario', 'Puede listar traslados inventario']],
            },
        ),
        migrations.CreateModel(
            name='TrasladoInventarioDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_realmente_trasladada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_traslados', to='productos.Producto')),
                ('traslado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='inventarios.TrasladoInventario')),
            ],
            options={
                'permissions': [['list_trasladoinventariodetalle', 'Puede listar traslados inventario detalle']],
            },
        ),
        migrations.AlterUniqueTogether(
            name='trasladoinventariodetalle',
            unique_together={('traslado', 'producto')},
        ),
        migrations.AlterUniqueTogether(
            name='movimientoinventariodetalle',
            unique_together={('movimiento', 'producto')},
        ),
    ]
