# Generated by Django 2.0.2 on 2018-03-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('es_principal', models.BooleanField(default=False)),
            ],
            options={
                'permissions': [['list_bodega', 'Puede listar bodegas']],
            },
        ),
    ]
