# Generated by Django 2.1.5 on 2019-03-19 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='cuenta',
        ),
        migrations.RemoveField(
            model_name='movimientoinventariodetalle',
            name='precio_venta_total',
        ),
    ]
