# Generated by Django 2.1.5 on 2019-02-23 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0004_tercero_qr_acceso'),
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='cuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compra_tienda', to='terceros.Cuenta'),
        ),
    ]
