# Generated by Django 2.1.5 on 2019-02-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_movimientoinventario_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventariodetalle',
            name='precio_venta_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
