# Generated by Django 2.0.2 on 2018-03-19 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_movimientoinventario_movimientoinventariodetalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='comprobante_numero',
        ),
    ]
