# Generated by Django 2.1.5 on 2019-03-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_auto_20190318_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventariodetalle',
            name='costo_unitario_promedio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
