# Generated by Django 2.1.5 on 2019-02-24 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0003_movimientoinventariodetalle_precio_venta_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='detalle',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='motivo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='observacion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventarios', to='terceros.Tercero'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
