# Generated by Django 2.1.5 on 2019-03-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0003_movimientoinventariodetalle_costo_unitario_promedio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trasladoinventario',
            name='estado',
            field=models.PositiveIntegerField(choices=[(1, 'Iniciado'), (2, 'Esperando Traslado'), (3, 'Verificado')], default=1),
        ),
    ]
