# Generated by Django 2.0.2 on 2018-03-19 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20180319_0500'),
        ('inventarios', '0003_remove_movimientoinventario_comprobante_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventariodetalle',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventarios', to='productos.Producto'),
            preserve_default=False,
        ),
    ]
