# Generated by Django 2.0.2 on 2018-03-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0004_movimientoinventariodetalle_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(default='EN', max_length=2),
            preserve_default=False,
        ),
    ]
