# Generated by Django 2.1.5 on 2019-03-23 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0005_auto_20190323_0102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trasladoinventariodetalle',
            options={'permissions': [['list_trasladoinventariodetalle', 'Puede listar traslados inventario detalle']]},
        ),
    ]
