# Generated by Django 2.0.2 on 2018-03-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0005_movimientoinventario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='detalle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
