# Generated by Django 2.0.2 on 2018-03-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0006_auto_20180319_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='motivo',
            field=models.TextField(default='inicial'),
            preserve_default=False,
        ),
    ]
