# Generated by Django 2.0.2 on 2018-03-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0008_movimientoinventario_creado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventariodetalle',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='movimientoinventariodetalle',
            name='entra_cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='movimientoinventariodetalle',
            name='entra_costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='movimientoinventariodetalle',
            name='saldo_cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='movimientoinventariodetalle',
            name='saldo_costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='movimientoinventariodetalle',
            name='sale_cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='movimientoinventariodetalle',
            name='sale_costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
