# Generated by Django 2.0.2 on 2018-03-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0010_movimientoinventario_cargado'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventariodetalle',
            name='es_ultimo_saldo',
            field=models.BooleanField(default=False),
        ),
    ]
