# Generated by Django 2.0.2 on 2018-03-23 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0011_movimientoinventariodetalle_es_ultimo_saldo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodega',
            options={'permissions': [['list_bodega', 'Puede listar bodegas'], ['detail_bodega', 'Puede ver detalle bodega']]},
        ),
    ]
