# Generated by Django 2.0.2 on 2018-03-23 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20180319_0500'),
        ('inventarios', '0012_auto_20180323_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrasladoInventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodega_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_mercancia_traslado', to='inventarios.Bodega')),
                ('bodega_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidad_mercancia_traslado', to='inventarios.Bodega')),
                ('movimiento_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslados_recibe', to='inventarios.MovimientoInventarioDetalle')),
                ('movimiento_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslados_entrega', to='inventarios.MovimientoInventarioDetalle')),
            ],
        ),
        migrations.CreateModel(
            name='TrasladoInventarioDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_traslados', to='productos.Producto')),
            ],
        ),
    ]
