# Generated by Django 2.0.2 on 2018-03-23 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0013_trasladoinventario_trasladoinventariodetalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trasladoinventario',
            name='movimiento_destino',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslado_recibe', to='inventarios.MovimientoInventario'),
        ),
        migrations.AlterField(
            model_name='trasladoinventario',
            name='movimiento_origen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslado_entrega', to='inventarios.MovimientoInventario'),
        ),
    ]
