# Generated by Django 2.0.2 on 2018-03-23 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0014_auto_20180323_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trasladoinventario',
            name='bodega_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas_mercancia_traslado', to='inventarios.Bodega'),
        ),
    ]
