# Generated by Django 2.0.2 on 2018-03-23 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0015_auto_20180323_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trasladoinventario',
            options={'permissions': [['list_trasladoinventario', 'Puede listar traslados inventario'], ['detail_trasladoinventario', 'Puede ver detalle traslados inventario']]},
        ),
    ]
