# Generated by Django 2.0.2 on 2018-03-24 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0016_auto_20180323_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='trasladoinventariodetalle',
            name='traslado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='inventarios.TrasladoInventario'),
            preserve_default=False,
        ),
    ]
