# Generated by Django 2.0.2 on 2018-03-24 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20180319_0500'),
        ('inventarios', '0018_auto_20180324_0540'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movimientoinventariodetalle',
            unique_together={('id', 'producto')},
        ),
        migrations.AlterUniqueTogether(
            name='trasladoinventariodetalle',
            unique_together={('id', 'producto')},
        ),
    ]
