# Generated by Django 2.0.2 on 2018-03-24 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20180319_0500'),
        ('inventarios', '0019_auto_20180324_1333'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movimientoinventariodetalle',
            unique_together={('movimiento', 'producto')},
        ),
        migrations.AlterUniqueTogether(
            name='trasladoinventariodetalle',
            unique_together={('traslado', 'producto')},
        ),
    ]
