# Generated by Django 2.0.2 on 2018-03-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0020_auto_20180324_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='trasladoinventario',
            name='trasladado',
            field=models.BooleanField(default=False),
        ),
    ]
