# Generated by Django 2.0.2 on 2018-03-24 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0022_trasladoinventariodetalle_costo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trasladoinventariodetalle',
            old_name='costo',
            new_name='costo_unitario',
        ),
    ]
