# Generated by Django 2.0.2 on 2018-03-24 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0023_auto_20180324_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trasladoinventariodetalle',
            old_name='costo_unitario',
            new_name='cantidad_realmente_trasladada',
        ),
    ]
