# Generated by Django 2.0.2 on 2018-03-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0024_auto_20180324_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
