# Generated by Django 2.2.7 on 2019-11-14 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_comprobantes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipocomprobantecontable',
            old_name='empresas',
            new_name='comprobantes_empresas',
        ),
    ]
