# Generated by Django 2.2.7 on 2019-11-14 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_comprobantes', '0002_auto_20191113_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipocomprobantecontable',
            options={'permissions': [['list_tipocomprobantecontable', 'Puede listar Tipos Comprobantes Contables']]},
        ),
        migrations.AlterModelOptions(
            name='tipocomprobantecontableempresa',
            options={'permissions': [['list_tipocomprobantecontableempresa', 'Puede listar Tipos Comprobantes Contables Empresas']]},
        ),
    ]
