# Generated by Django 2.2.7 on 2019-11-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_comprobantes', '0003_auto_20191113_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocomprobantecontableempresa',
            name='numero_autorizacion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
