# Generated by Django 2.2.7 on 2019-11-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_comprobantes', '0006_auto_20191116_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocomprobantecontableempresa',
            name='ciudad_emision',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tipocomprobantecontableempresa',
            name='direccion_emision',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tipocomprobantecontableempresa',
            name='pais_emision',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tipocomprobantecontableempresa',
            name='telefono_emision',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
