# Generated by Django 2.0.2 on 2018-03-13 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula Ciudadanía'), ('CE', 'Cédula Extrangería'), ('PS', 'Pasaporte'), ('TI', 'Tarjeta Identidad')], default='CC', max_length=2)),
                ('nro_identificacion', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('nombre_segundo', models.CharField(blank=True, max_length=60, null=True)),
                ('apellido', models.CharField(max_length=60)),
                ('apellido_segundo', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=20)),
                ('grupo_sanguineo', models.CharField(blank=True, max_length=60, null=True)),
                ('es_acompanante', models.BooleanField(default=False)),
                ('es_colaborador', models.BooleanField(default=False)),
                ('alias', models.CharField(blank=True, max_length=120, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tercero', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tercero',
            unique_together={('tipo_documento', 'nro_identificacion')},
        ),
    ]
