# Generated by Django 2.2.7 on 2019-11-19 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields
import model_utils.fields
import terceros.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terceros_acompanantes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('liquidada', models.BooleanField(db_index=True, default=False)),
                ('tipo', models.PositiveIntegerField(choices=[(1, 'Propia'), (2, 'Mesero')], default=1)),
                ('cuenta_anterior', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_siguiente', to='terceros.Cuenta')),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula Ciudadanía'), ('CE', 'Cédula Extrangería'), ('PS', 'Pasaporte'), ('TI', 'Tarjeta Identidad'), ('NI', 'Nit')], default='CC', max_length=2)),
                ('nro_identificacion', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=400)),
                ('nombre_segundo', models.CharField(blank=True, max_length=60, null=True)),
                ('apellido', models.CharField(blank=True, max_length=60, null=True)),
                ('apellido_segundo', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=20, null=True)),
                ('grupo_sanguineo', models.CharField(max_length=60, null=True)),
                ('es_acompanante', models.BooleanField(default=False)),
                ('es_colaborador', models.BooleanField(default=False)),
                ('es_proveedor', models.BooleanField(default=False)),
                ('presente', models.BooleanField(default=False)),
                ('pin', models.CharField(max_length=128, null=True)),
                ('qr_acceso', models.CharField(max_length=300, null=True)),
                ('imagen_perfil', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=terceros.models.Tercero.imagen_perfil_upload_to)),
                ('alias_modelo', models.CharField(error_messages={'unique': 'Este alias ya esta siendo utilizado por otra modelo. Por favor escoger otro'}, max_length=120, null=True, unique=True)),
                ('estado', models.PositiveIntegerField(choices=[(0, 'Disponible'), (1, 'Ocupado')], default=0)),
                ('categoria_modelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acompanantes', to='terceros_acompanantes.CategoriaAcompanante')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tercero', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [['list_tercero', 'Puede listar terceros'], ['view_terceroacompanante', 'Can view acompanantes'], ['view_privado_terceroacompanante', 'Can view acompanantes privado'], ['add_terceroacompanante', 'Puede adicionar acompanantes'], ['delete_terceroacompanante', 'Puede eliminar acompanantes'], ['change_terceroacompanante', 'Puede cambiar acompanantes'], ['list_terceroacompanante', 'Puede listar acompanantes'], ['view_tercerocolaborador', 'Can view colaboradores'], ['add_tercerocolaborador', 'Puede adicionar colaboradores'], ['delete_tercerocolaborador', 'Puede eliminar colaboradores'], ['change_tercerocolaborador', 'Puede cambiar colaboradores'], ['list_tercerocolaborador', 'Puede listar colaboradores'], ['view_terceroproveedor', 'Can view proveedores'], ['add_terceroproveedor', 'Puede adicionar proveedores'], ['delete_terceroproveedor', 'Puede eliminar proveedores'], ['change_terceroproveedor', 'Puede cambiar proveedores'], ['list_terceroproveedor', 'Puede listar proveedores'], ['can_be_waiter', 'Puede Ser Mesero(a)']],
                'unique_together': {('tipo_documento', 'nro_identificacion')},
            },
        ),
    ]
