# Generated by Django 2.0.2 on 2018-07-17 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terceros_acompanantes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('liquidada', models.BooleanField(db_index=True, default=False)),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula Ciudadanía'), ('CE', 'Cédula Extrangería'), ('PS', 'Pasaporte'), ('TI', 'Tarjeta Identidad'), ('NI', 'Nit')], default='CC', max_length=2)),
                ('nro_identificacion', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=400)),
                ('nombre_segundo', models.CharField(blank=True, max_length=60, null=True)),
                ('apellido', models.CharField(blank=True, max_length=60, null=True)),
                ('apellido_segundo', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=20, null=True)),
                ('grupo_sanguineo', models.CharField(blank=True, max_length=60, null=True)),
                ('es_acompanante', models.BooleanField(default=False)),
                ('es_colaborador', models.BooleanField(default=False)),
                ('es_proveedor', models.BooleanField(default=False)),
                ('presente', models.BooleanField(default=False)),
                ('pin', models.CharField(max_length=128, null=True)),
                ('alias_modelo', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('estado', models.PositiveIntegerField(choices=[(0, 'Disponible'), (1, 'Ocupado')], default=0)),
                ('categoria_modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acompanantes', to='terceros_acompanantes.CategoriaAcompanante')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tercero', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [['list_terceroacompanante', 'Puede listar acompanantes'], ['detail_terceroacompanante', 'Puede ver detalles acompanantes'], ['add_terceroacompanante', 'Puede adicionar acompanantes'], ['delete_terceroacompanante', 'Puede eliminar acompanantes'], ['change_terceroacompanante', 'Puede cambiar acompanantes'], ['list_tercerocolaborador', 'Puede listar colaboradores'], ['detail_tercerocolaborador', 'Puede ver detalles colaboradores'], ['add_tercerocolaborador', 'Puede adicionar colaboradores'], ['delete_tercerocolaborador', 'Puede eliminar colaboradores'], ['change_tercerocolaborador', 'Puede cambiar colaboradores'], ['list_terceroproveedor', 'Puede listar proveedores'], ['detail_terceroproveedor', 'Puede ver detalles proveedores'], ['add_terceroproveedor', 'Puede adicionar proveedores'], ['delete_terceroproveedor', 'Puede eliminar proveedores'], ['change_terceroproveedor', 'Puede cambiar proveedores']],
            },
        ),
        migrations.AlterUniqueTogether(
            name='tercero',
            unique_together={('tipo_documento', 'nro_identificacion')},
        ),
    ]
