# Generated by Django 2.1.5 on 2019-03-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tercero',
            name='alias_modelo',
            field=models.CharField(error_messages={'unique': 'Este alias ya esta siendo utilizado por otra modelo. Por favor escoger otro'}, max_length=120, null=True, unique=True),
        ),
    ]
