# Generated by Django 2.0.2 on 2018-03-13 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terceros_acompanantes', '0001_initial'),
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tercero',
            name='alias',
        ),
        migrations.AddField(
            model_name='tercero',
            name='alias_modelo',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tercero',
            name='categoria_modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='terceros_acompanantes.CategoriaAcompanante'),
        ),
    ]
