# Generated by Django 2.1.5 on 2019-02-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tercero',
            name='imagen_perfil',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
