# Generated by Django 2.1.5 on 2019-03-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='saldo_anterior',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='saldo_pasa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='valor_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
