# Generated by Django 2.0.2 on 2018-03-13 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0002_auto_20180313_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tercero',
            options={'permissions': [['list_terceroacompanante', 'Puede listar acompanantes'], ['detail_terceroacompanante', 'Puede ver detalles acompanantes'], ['add_terceroacompanante', 'Puede adicionar acompanantes'], ['delete_terceroacompanante', 'Puede eliminar acompanantes'], ['change_terceroacompanante', 'Puede cambiar acompanantes'], ['list_tercerocolaborador', 'Puede listar colaboradores'], ['detail_tercerocolaborador', 'Puede ver detalles colaboradores'], ['add_tercerocolaborador', 'Puede adicionar colaboradores'], ['delete_tercerocolaborador', 'Puede eliminar colaboradores'], ['change_tercerocolaborador', 'Puede cambiar colaboradores']]},
        ),
        migrations.AlterField(
            model_name='tercero',
            name='categoria_modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acompanantes', to='terceros_acompanantes.CategoriaAcompanante'),
        ),
    ]
