# Generated by Django 2.1.5 on 2019-03-13 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0002_auto_20190309_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='saldo_anterior',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='saldo_pasa',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='valor_pagado',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='categoria_modelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acompanantes', to='terceros_acompanantes.CategoriaAcompanante'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='grupo_sanguineo',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
