# Generated by Django 2.1.5 on 2019-02-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0003_auto_20190218_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='tercero',
            name='qr_acceso',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
