# Generated by Django 2.0.2 on 2018-03-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0003_auto_20180313_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='tercero',
            name='es_proveedor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='apellido',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='genero',
            field=models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula Ciudadanía'), ('CE', 'Cédula Extrangería'), ('PS', 'Pasaporte'), ('TI', 'Tarjeta Identidad'), ('NI', 'Nit')], default='CC', max_length=2),
        ),
    ]
