# Generated by Django 2.2 on 2019-05-02 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0003_auto_20190501_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='cuenta_anterior',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_siguiente', to='terceros.Cuenta'),
        ),
    ]
