# Generated by Django 2.0.2 on 2018-03-19 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0004_auto_20180319_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tercero',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tercero', to=settings.AUTH_USER_MODEL),
        ),
    ]
