# Generated by Django 2.1.5 on 2019-02-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0004_tercero_qr_acceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Propia'), (2, 'Mesero')], default=1),
        ),
    ]
