# Generated by Django 2.2 on 2019-05-02 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0004_cuenta_cuenta_anterior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='cuenta_anterior',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_siguiente', to='terceros.Cuenta'),
        ),
    ]
