# Generated by Django 2.0.2 on 2018-03-19 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0005_auto_20180319_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tercero',
            options={'permissions': [['list_terceroacompanante', 'Puede listar acompanantes'], ['detail_terceroacompanante', 'Puede ver detalles acompanantes'], ['add_terceroacompanante', 'Puede adicionar acompanantes'], ['delete_terceroacompanante', 'Puede eliminar acompanantes'], ['change_terceroacompanante', 'Puede cambiar acompanantes'], ['list_tercerocolaborador', 'Puede listar colaboradores'], ['detail_tercerocolaborador', 'Puede ver detalles colaboradores'], ['add_tercerocolaborador', 'Puede adicionar colaboradores'], ['delete_tercerocolaborador', 'Puede eliminar colaboradores'], ['change_tercerocolaborador', 'Puede cambiar colaboradores'], ['list_terceroproveedor', 'Puede listar proveedores'], ['detail_terceroproveedor', 'Puede ver detalles proveedores'], ['add_terceroproveedor', 'Puede adicionar proveedores'], ['delete_terceroproveedor', 'Puede eliminar proveedores'], ['change_terceroproveedor', 'Puede cambiar proveedores']]},
        ),
    ]
