# Generated by Django 2.0.2 on 2018-03-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0006_auto_20180319_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tercero',
            name='nombre',
            field=models.CharField(max_length=400),
        ),
    ]
