# Generated by Django 2.0.2 on 2018-06-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0007_auto_20180319_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='tercero',
            name='presente',
            field=models.BooleanField(default=False),
        ),
    ]
