# Generated by Django 2.0.2 on 2018-06-12 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0011_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='liquidada',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
