# Generated by Django 2.2.7 on 2019-11-20 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad_impuestos', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDosProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'permissions': [['list_categoriadosproducto', 'Puede listar categorias dos productos']],
            },
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'permissions': [['list_categoriaproducto', 'Puede listar categorias productos']],
            },
        ),
        migrations.CreateModel(
            name='UnidadProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'permissions': [['list_unidadproducto', 'Puede listar unidades productos']],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comision', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('categoria_dos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='productos.CategoriaDosProducto')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='empresas.Empresa')),
                ('impuestos', models.ManyToManyField(related_name='productos', to='contabilidad_impuestos.Impuesto')),
                ('unidad_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='productos.UnidadProducto')),
            ],
            options={
                'permissions': [['list_producto', 'Puede listar productos']],
            },
        ),
        migrations.AddField(
            model_name='categoriadosproducto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias_dos', to='productos.CategoriaProducto'),
        ),
    ]
