# Generated by Django 2.0.2 on 2018-07-17 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('codigo', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'permissions': [['list_categoria', 'Puede listar categorias productos']],
            },
        ),
        migrations.CreateModel(
            name='CategoriaDos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('codigo', models.CharField(max_length=3, unique=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias_dos', to='productos.Categoria')),
            ],
            options={
                'permissions': [['list_categoriados', 'Puede listar categorias dos productos']],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('categoria_dos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='productos.CategoriaDos')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='empresas.Empresa')),
            ],
            options={
                'permissions': [['list_producto', 'Puede listar productos']],
            },
        ),
        migrations.CreateModel(
            name='UnidadProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'permissions': [['list_unidadproducto', 'Puede listar unidades productos']],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='productos.UnidadProducto'),
        ),
    ]
