# Generated by Django 2.1.5 on 2019-03-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriadosproducto',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='categoriaproducto',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
