# Generated by Django 2.0.2 on 2018-03-19 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'permissions': [['list_categoria', 'Puede listar categorias productos']]},
        ),
        migrations.AlterModelOptions(
            name='categoriados',
            options={'permissions': [['list_categoriados', 'Puede listar categorias dos productos']]},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'permissions': [['list_producto', 'Puede listar productos']]},
        ),
        migrations.AlterModelOptions(
            name='unidadproducto',
            options={'permissions': [['list_unidadproducto', 'Puede listar unidades productos']]},
        ),
    ]
