# Generated by Django 2.2.7 on 2019-11-20 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad_diario', '0001_initial'),
        ('contabilidad_bancos', '0001_initial'),
        ('contabilidad_cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.IntegerField(choices=[(1, 'Efectivo'), (2, 'Bancario'), (3, 'Credito Mesero'), (4, 'Credito Tercero')])),
                ('cuenta_bancaria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metodos_de_pago', to='contabilidad_bancos.CuentaBancariaBanco')),
                ('cuenta_metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metodos_pagos', to='contabilidad_cuentas.CuentaContable')),
                ('cuenta_metodo_pago_devolucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metodos_pagos_devolucion', to='contabilidad_cuentas.CuentaContable')),
                ('diario_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad_diario.DiarioContable')),
            ],
            options={
                'permissions': [['list_metodopago', 'Puede listar Métodos de Pagos']],
            },
        ),
    ]
