# Generated by Django 2.2.7 on 2019-11-12 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_metodos_pago', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metodopago',
            options={'permissions': [['list_metodopago', 'Puede listar Métodos de Pagos']]},
        ),
    ]
