# Generated by Django 2.2.7 on 2019-11-13 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_metodos_pago', '0002_auto_20191111_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metodopago',
            name='diario_contable',
        ),
    ]
