# Generated by Django 2.2.3 on 2019-07-14 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_bancos', '0002_auto_20190510_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentabancariabanco',
            name='banco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad_bancos.Banco'),
        ),
    ]
