# Generated by Django 2.1.5 on 2019-03-27 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAcompanante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'permissions': [['list_categoriaacompanante', 'Puede listar categorias acompanantes']],
            },
        ),
        migrations.CreateModel(
            name='CategoriaFraccionTiempo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fracciones', to='terceros_acompanantes.CategoriaAcompanante')),
            ],
            options={
                'permissions': [['list_categoriafracciontiempo', 'Puede listar fraciones de tiempo x categoria']],
            },
        ),
        migrations.CreateModel(
            name='FraccionTiempo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutos', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'permissions': [['list_fracciontiempo', 'Puede listar fraciones de tiempo']],
            },
        ),
        migrations.AddField(
            model_name='categoriafracciontiempo',
            name='fraccion_tiempo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='terceros_acompanantes.FraccionTiempo'),
        ),
        migrations.AlterUniqueTogether(
            name='categoriafracciontiempo',
            unique_together={('categoria', 'fraccion_tiempo')},
        ),
    ]
