# Generated by Django 2.0.2 on 2018-06-11 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terceros_acompanantes', '0002_auto_20180313_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFraccionTiempo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fracciones', to='terceros_acompanantes.CategoriaAcompanante')),
            ],
        ),
        migrations.CreateModel(
            name='FraccionTiempo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutos', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='categoriafracciontiempo',
            name='fraccion_tiempo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='terceros_acompanantes.FraccionTiempo'),
        ),
    ]
