# Generated by Django 2.0.2 on 2018-06-11 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terceros_acompanantes', '0003_auto_20180611_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriafracciontiempo',
            options={'permissions': [['list_categoriafracciontiempo', 'Puede listar fraciones de tiempo x categoria']]},
        ),
        migrations.AlterModelOptions(
            name='fracciontiempo',
            options={'permissions': [['list_fracciontiempo', 'Puede listar fraciones de tiempo']]},
        ),
    ]
