# Generated by Django 2.0.2 on 2018-06-12 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terceros_acompanantes', '0004_auto_20180611_2153'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categoriafracciontiempo',
            unique_together={('categoria', 'fraccion_tiempo')},
        ),
    ]
