# Generated by Django 2.2 on 2019-05-08 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_comprobante', models.CharField(max_length=300)),
                ('titulo_interno', models.CharField(max_length=300)),
                ('activo', models.BooleanField(default=False)),
                ('nro_resolucion_dian', models.CharField(max_length=100)),
                ('consecutivo', models.IntegerField()),
                ('prefijo', models.CharField(max_length=10)),
                ('numero_inicial', models.IntegerField()),
                ('numero_final', models.IntegerField()),
                ('fecha_autorizacion', models.DateTimeField()),
                ('no_mostrar_mensaje_resolucion', models.BooleanField(default=False)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes', to='empresas.Empresa')),
            ],
        ),
    ]
