# Generated by Django 2.0.2 on 2018-03-19 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'permissions': [['list_empresa', 'Puede listar empresas']]},
        ),
    ]
