# Generated by Django 2.2 on 2019-07-03 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aditionaldefaultpermission',
            options={'managed': False, 'permissions': (('list_user', 'Can list user'), ('list_permission', 'Can list permission'), ('list_group', 'Can list group'), ('change_user_permission', 'Can change user permission'), ('make_user_superuser', 'Can make user superuser'), ('make_user_staff', 'Can make user staff'), ('make_user_active', 'Can make user active'))},
        ),
    ]
