# Generated by Django 2.2.3 on 2019-07-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0002_auto_20190703_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuAdminPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('menu_admin_empresas', 'Menu Admin Empresas'), ('menu_admin_habitaciones', 'Menu Admin Habitaciones'), ('menu_admin_productos', 'Menu Admin Productos'), ('menu_admin_puntos_ventas', 'Menu Admin Puntos Ventas'), ('menu_admin_parqueadero', 'Menu Admin Parqueadero'), ('menu_admin_permisos', 'Menu Admin Permisos'), ('menu_admin_permisos_grupos', 'Menu Admin Grupos Permisos'), ('menu_admin_terceros_usuarios', 'Menu Admin Terceros Usuarios'), ('menu_admin_terceros_acompanantes', 'Menu Admin Terceros Acompanantes'), ('menu_admin_terceros_colaboradores', 'Menu Admin Terceros Colaboradores'), ('menu_admin_terceros_proveedores', 'Menu Admin Terceros Proveedores')),
                'managed': False,
            },
        ),
    ]
