# Generated by Django 2.2.7 on 2019-11-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0005_auto_20190703_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('modulo_admin', 'Modulo Administracion'), ('modulo_mi_cuenta', 'Modulo Mi Cuenta'), ('modulo_acceso', 'Modulo Acceso'), ('modulo_consultas', 'Modulo Consultas')),
                'managed': False,
            },
        ),
    ]
