# Generated by Django 2.2 on 2019-05-10 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apuntecontable',
            options={'permissions': [['list_apuntecontable', 'Puede listar Apuntes Contables']]},
        ),
        migrations.AlterModelOptions(
            name='asientocontable',
            options={'permissions': [['list_asientocontable', 'Puede listar Asientos Contables']]},
        ),
    ]
