# Generated by Django 2.2 on 2019-05-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_movimientos', '0002_auto_20190510_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asientocontable',
            name='nota',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
