# Generated by Django 2.2.6 on 2019-11-04 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0005_auto_20190502_0121'),
        ('contabilidad_movimientos', '0003_auto_20190511_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='apuntecontable',
            name='tercero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apuntes_contables', to='terceros.Tercero'),
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asientos_contables', to='empresas.Empresa'),
        ),
    ]
