# Generated by Django 2.2.7 on 2019-11-14 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_movimientos', '0006_auto_20191113_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apuntecontable',
            name='apunte_contable_cierre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asientos_contables_cerrados', to='contabilidad_movimientos.ApunteContable'),
        ),
    ]
