# Generated by Django 2.1.5 on 2019-03-27 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('puntos_venta', '0001_initial'),
        ('terceros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidacionCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('pagado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_efectuadas', to=settings.AUTH_USER_MODEL)),
                ('cuenta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liquidacion', to='terceros.Cuenta')),
                ('punto_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='puntos_venta.PuntoVenta')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
