# Generated by Django 2.1.5 on 2019-03-30 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0001_initial'),
        ('puntos_venta', '0001_initial'),
        ('liquidaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidacioncuenta',
            name='punto_venta',
        ),
        migrations.AddField(
            model_name='liquidacioncuenta',
            name='punto_venta_turno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='puntos_venta.PuntoVentaTurno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liquidacioncuenta',
            name='transacciones_caja',
            field=models.ManyToManyField(related_name='liquidaciones', to='cajas.TransaccionCaja'),
        ),
        migrations.AlterField(
            model_name='liquidacioncuenta',
            name='pagado',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacioncuenta',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
