# Generated by Django 2.1.5 on 2019-03-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidaciones', '0002_auto_20190330_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacioncuenta',
            name='saldo_anterior',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
