# Generated by Django 2.1.5 on 2019-03-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidaciones', '0004_remove_liquidacioncuenta_creado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacioncuenta',
            name='actual_a_pagar',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
