# Generated by Django 2.1.5 on 2019-03-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidaciones', '0005_liquidacioncuenta_actual_a_pagar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacioncuenta',
            name='actual_a_pagar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='liquidacioncuenta',
            name='pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='liquidacioncuenta',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='liquidacioncuenta',
            name='saldo_anterior',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
