# Generated by Django 2.1.5 on 2019-03-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidaciones', '0006_auto_20190331_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacioncuenta',
            name='efectivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='liquidacioncuenta',
            name='transferencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
