# Generated by Django 2.1.5 on 2019-03-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidaciones', '0008_auto_20190331_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacioncuenta',
            name='a_cobrar_a_tercero',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='liquidacioncuenta',
            name='a_pagar_a_tercero',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
