# Generated by Django 2.1.5 on 2019-03-31 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquidaciones', '0009_auto_20190331_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidacioncuenta',
            name='actual_a_pagar',
        ),
    ]
