# Generated by Django 2.1.5 on 2019-04-01 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('liquidaciones', '0010_remove_liquidacioncuenta_actual_a_pagar'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacioncuenta',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='liquidacioncuenta',
            name='punto_venta_turno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='puntos_venta.PuntoVentaTurno'),
        ),
    ]
