# Generated by Django 2.1.5 on 2019-04-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidaciones', '0011_auto_20190401_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacioncuenta',
            name='fecha_liquidacion',
            field=models.DateTimeField(null=True),
        ),
    ]
