# Generated by Django 2.1.5 on 2019-04-23 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquidaciones', '0012_liquidacioncuenta_fecha_liquidacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidacioncuenta',
            name='fecha_liquidacion',
        ),
    ]
